
business_types = {
    
    'Accountants': {'yelp': 'accountants', 'google': 'accounting'},
    'Airports': {'yelp': 'airports', 'google': 'airport'},
    'Amusement Parks': {'yelp': 'amusementparks', 'google': 'amusement_park'},
    'Aquariums': {'yelp': 'aquariums', 'google': 'aquarium'},
    'Art Galleries': {'yelp': 'galleries', 'google': 'art_gallery'},
    'Bakeries': {'yelp': 'bakeries', 'google': 'bakery'},
    'Banks': {'yelp': 'banks', 'google': 'bank'},
    'Bars': {'yelp': 'bars', 'google': 'bar'},
    'Beauty Services': {'yelp': 'beautysvc, hair', 'google': 'beauty_salon'},
    'Bicycles': {'yelp': 'bicycles', 'google': 'bicycle_store'},
    'Bookstores': {'yelp': 'bookstores', 'google': 'book_store'},
    'Bowling Alleys': {'yelp': 'bowling', 'google': 'bowling_alley'},
    'Cafes': {'yelp': 'cafes', 'google': 'cafe'},
    'Car Dealerships': {'yelp': 'car_dealers', 'google': 'car_dealer'},
    'Car Rentals': {'yelp': 'carrental', 'google': 'car_rental'},
    'Auto Repair': {'yelp': 'autorepair', 'google': 'car_repair'},
    'Car Wash': {'yelp': 'carwash', 'google': 'car_wash'},
    'Casinos': {'yelp': 'casinos', 'google': 'casino'},
    'Churches': {'yelp': 'churches', 'google': 'church'},
    'Fashion': {'yelp': 'fashion', 'google': 'clothing_store'},
    'Convenience Stores': {'yelp': 'convenience', 'google': 'convenience_store'},
    'Dentists': {'yelp': 'dentists', 'google': 'dentist'},
    'Department Stores': {'yelp': 'deptstores', 'google': 'department_store'},
    'Doctors': {'yelp': 'physicians', 'google': 'doctor'},
    'Drugstores': {'yelp': 'drugstores', 'google': 'drugstore'},
    'Electricians': {'yelp': 'electricians', 'google': 'electrician'},
    'Electronics': {'yelp': 'electronics', 'google': 'electronics_store'},
    'Florists': {'yelp': 'florists', 'google': 'florist'},
    'Furniture': {'yelp': 'furniture', 'google': 'furniture_store'},
    'Gas Stations': {'yelp': 'servicestations', 'google': 'gas_station'},
    'Gyms': {'yelp': 'gyms', 'google': 'gym'},
    'Hair Salons': {'yelp': 'hair, barbers', 'google': 'hair_care'},
    'Hardware Stores': {'yelp': 'hardware', 'google': 'hardware_store'},
    'Home Goods': {'yelp': 'homeandgarden', 'google': 'home_goods_store'},
    'Hospitalists': {'yelp': 'hospitalists', 'google': 'hospital'},
    'Insurance': {'yelp': 'insurance', 'google': 'insurance_agency'},
    'Jewelry': {'yelp': 'jewelry', 'google': 'jewelry_store'},
    'Laundry Services': {'yelp': 'laundryservices', 'google': 'laundry'},
    'Lawyers': {'yelp': 'lawyers', 'google': 'lawyer'},
    'Locksmiths': {'yelp': 'locksmiths', 'google': 'locksmith'},
    'Food Delivery Services': {'yelp': 'fooddeliveryservices', 'google': 'meal_delivery'},
    'Movie Theaters': {'yelp': 'movietheaters', 'google': 'movie_theater'},
    'Movers': {'yelp': 'movers', 'google': 'moving_company'},
    'Nightlife': {'yelp': 'nightlife', 'google': 'night_club'},
    'Painters': {'yelp': 'painters', 'google': 'painter'},
    'Parking': {'yelp': 'parking', 'google': 'parking'},
    'Pet Store': {'yelp': 'petstore', 'google': 'pet_store'},
    'Pharmacy': {'yelp': 'pharmacy', 'google': 'pharmacy'},
    'Physical Therapy': {'yelp': 'physicaltherapy', 'google': 'physiotherapist'},
    'Plumbing': {'yelp': 'plumbing', 'google': 'plumber'},
    'Real Estate': {'yelp': 'realestate', 'google': 'real_estate_agency'},
    'Restaurants': {'yelp': 'restaurants', 'google': 'restaurant'},
    'Roofing': {'yelp': 'roofing', 'google': 'roofing_contractor'},
    'Shoes': {'yelp': 'shoes', 'google': 'shoe_store'},
    'Shopping': {'yelp': 'shopping', 'google': 'shopping_mall'},
    'Spas': {'yelp': 'spas', 'google': 'spa'},
    'Storage': {'yelp': 'selfstorage', 'google': 'storage'},
    'Grocery Stores': {'yelp': 'grocery', 'google': 'supermarket'},
    'Hotels and Travel': {'yelp': 'hotelstravel', 'google': 'travel_agency'},
    'Veterinary': {'yelp': 'vet', 'google': 'veterinary_care'},
    'Zoos': {'yelp': 'zoos', 'google': 'zoo'}

}
